### ISSUE TITLE
Cannot import when installed from pypi because domains not found

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-maps#14]
### What happened?

When I install earthkit-maps from pypi with `pip install earthkit-maps` I cannot import it because :

```python
import earthkit.maps
```

raises:

```
earthkit/maps/data.py", line 54, in load
    raise DataNotFoundError(f"could not find data named '{source}'")
earthkit.maps.data.DataNotFoundError: could not find data named 'domains'
```

### What are the steps to reproduce the bug?

See above

### Version

0.0.5

### Platform (OS and architecture)

all

### Organisation

ECMWF

**Comment by JamesVarndell** [comment]
This issue has been resolved
