### ISSUE TITLE
Reasoning for style structure?

### ISSUE THREAD

**Issue by HCookie** [ecmwf/earthkit-maps#30]
### Is your feature request related to a problem? Please describe.

When specifying another `style_library`, all default styles are no longer active. I am curious as to why this is the case?

I would have expected the default to remain active and be overwritten by the chosen library if it has specified it.

E.g.
ecmwf specified temperature but does not specify mslp.
Should than the default still be used?

### Describe the solution you'd like

I think that using default as the default to be overwritten may help.
I am prototyping a solution on my fork currently.

### Organisation

Australian Bureau of Meteorology

**Comment by JamesVarndell** [comment]
Hi @HCookie, thanks for raising this issue. I completely agree with your suggestion here - when a style cannot be found in the current library, earthkit-maps should fall back to the default style library. Thanks for your PR - I will review it now.

**Comment by JamesVarndell** [comment]
Merged in #29. Closing now - thanks again for the implementation.

**Comment by HCookie** [comment]
Hi,

This issue was discussing another pr that is sitting on my fork. 
That pr was concerning user defined schemas.

**Comment by HCookie** [comment]
I have created a new pull request to address this issue
