### ISSUE TITLE
Implement default style

### ISSUE THREAD

**Issue by HCookie** [ecmwf/earthkit-maps#32]
### Is your feature request related to a problem? Please describe.

As discussed in #30, it would be beneficial to alter how styles are chosen.

### Describe the solution you'd like

This implementation will use the default styles by default or use any overriden styles defined by the schema.

### Additional context

Issue #30, was closed in reference to another pull request which had no associated issue, #29. Instead #31 implements this feature.

### Organisation

Australian Bureau of Meteorology

**Comment by HCookie** [comment]
Will this issue be resolved through the associated merge request?

**Comment by JamesVarndell** [comment]
This issue has been resolved in #29
