### ISSUE TITLE
Cannot import when installed from pypi because cv2 is missing

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-maps#7]
### What happened?

When I install earthkit-maps from pypi with `pip install earthkit-maps` I cannot import it because `cv2` is not found:

```python
import earthkit.maps

...

E   ModuleNotFoundError: No module named 'cv2'
```

### What are the steps to reproduce the bug?

See above

### Version

0.0.1

### Platform (OS and architecture)

macOS

**Comment by JamesVarndell** [comment]
Open-CV has now been removed as a dependency
