### ISSUE TITLE
Misaligned legend when using quickplot for two fields

### ISSUE THREAD

**Issue by sandorkertesz** [ecmwf/earthkit-maps#8]
### What happened?

If I use this code (develop branch):

```python
import earthkit.data
from earthkit.maps.quickplot import quickplot

earthkit.data.download_example_file("test.grib")
data = earthkit.data.from_source("file", "test.grib")

quickplot(data)
```

I get this plot in a notebook:

<img width="806" alt="image" src="https://github.com/ecmwf/earthkit-maps/assets/9033020/dc099fbd-4c1f-45b2-9161-481d1cce2a51">

### What are the steps to reproduce the bug?

See above

### Version

develop

### Platform (OS and architecture)

macOS

### Organisation

ECMWF

**Comment by JamesVarndell** [comment]
Closing as this has been fixed during development.
